# Generated by Django 4.1.7 on 2023-03-09 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                ("budgetId", models.AutoField(primary_key=True, serialize=False)),
                ("ownerId", models.IntegerField()),
                ("setBudget", models.IntegerField()),
                ("startDate", models.DateTimeField()),
                ("modifyTime", models.DateTimeField()),
            ],
            options={"db_table": "budget",},
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                ("groupId", models.AutoField(primary_key=True, serialize=False)),
                ("adminId", models.IntegerField()),
                ("billList", models.CharField(max_length=255)),
                ("numMembers", models.IntegerField()),
            ],
            options={"db_table": "group",},
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("transactionId", models.AutoField(primary_key=True, serialize=False)),
                ("ownerId", models.IntegerField()),
                ("values", models.FloatField()),
                ("category", models.IntegerField()),
                ("createTime", models.DateTimeField()),
                ("description", models.CharField(max_length=32)),
            ],
            options={"db_table": "transaction",},
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("userId", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=30)),
                ("groupId", models.IntegerField()),
                ("email", models.CharField(max_length=32)),
                ("totalExpenses", models.IntegerField()),
                ("status", models.IntegerField()),
                ("role", models.IntegerField()),
            ],
            options={"db_table": "user",},
        ),
    ]
